node {
    // first repository
    checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'src']], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/BalaRB/MyJavaProject.git']]])
    // run first script
    load 'src/Jenkinsfile'
}
